# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjA0ZjU4ODA4YzIzNjdiOWRjNmE5ZmJiZGM3Y2YyODE1NGFlNDY4Yjc0N2RjOWJkM2JmZmU5M2NlNzhjZDZkYzU0NWQ5ODE2MTI5OGM3YjdkN2Y1NzQ3Yzc5NzBjYWQwZThhNmNlMzFjNTE0MDkwN2Q4NTIzNWM4MjZmZDZmNmY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
